spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  main:
    allow-bean-definition-overriding: true
  endpoints:
    web:
      exposure:
        include: "*"

  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

info:
  app:
    name: Gateway Server Microservice
    description: Fintech Bank Accounts Application
    version: 1.0.0

logging:
  level:
    com:
      example:
        gatewayServer: DEBUG
    org.springframework.web: DEBUG
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka/
#  instance:
#    hostname: localhost