server:
  port: 8093
#  servlet:
#    context-path : /api
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: accounts
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071/
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.web: DEBUG

app:
  base:
    url: http://localhost:8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

info:
  app:
    name: Accounts Microservice
    description: Fintech Bank Accounts Application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
      configs:
        default:
          registerHealthIndicator: true
      instances:
        detailsForCustomer:
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 30000
          permittedNumberOfCallsInHalfOpenState: 2
  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      retryForCustomerDetails:
        maxRetryAttempts: 3
        waitDuration: 2000
